# Generated by Django 2.2 on 2021-06-22 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.PositiveIntegerField(choices=[(1, 'DNI'), (2, 'Carnet de Extranjeria'), (3, 'Pasaporte')])),
                ('document_number', models.CharField(max_length=45)),
                ('birthdate', models.DateField(null=True)),
                ('phone', models.CharField(blank=True, max_length=25)),
                ('father_last_name', models.CharField(max_length=150)),
                ('mother_last_name', models.CharField(max_length=150)),
                ('email_score', models.CharField(blank=True, max_length=150)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('entry_date', models.DateField(null=True)),
                ('termination_date', models.DateField(null=True)),
                ('sex', models.CharField(blank=True, choices=[('m', 'Masculino'), ('f', 'Femenino')], max_length=1)),
            ],
        ),
    ]
