version: '3'
services:
    web:
        build: .
        command: python3 manage.py runserver 0.0.0.0:8000
        volumes:
          - .:/app
        ports:
          - 8000:8000
        env_file:
          - ./.env.dev
        depends_on:
          - db
        networks:
          tenant:
            aliases:
              - web

    db:
      image: postgres:13.0-alpine
      ports:
        - "54320:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      environment:
         - POSTGRES_USER=hello_django
         - POSTGRES_PASSWORD=hello_django
         - POSTGRES_DB=django_tenant_dev
      networks:
        tenant:
          aliases:
            - db


networks:
  tenant:


volumes:
    postgres_data:
